name: Docker PHP Images GitHub workflow

on:
  push:
    branches:
      - 'minimalist'

jobs:
  build_test_maybe_release:
    strategy:
      matrix:
        include:
          - variant: 'minimalist'
            php_version: '8.1'
          - variant: 'minimalist'
            php_version: '7.4'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v1
      - name: Build and test
        run: |
          VERSION=${{ matrix.php_version }}
          TAG="${{ matrix.php_version }}-${{ matrix.variant }}"
          make build
          docker images | grep raneomik/symfony-cli
      - name: Login to DockerHub
        # Merge ~ push.
        if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Release
        # Merge ~ push.
        if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
        run: |
          VERSION=${{ matrix.php_version }}
          TAG="${{ matrix.php_version }}-${{ matrix.variant }}"
          make tag push
